account/urls.py
from django.conf.urls import url, include
from account.views import logout_page, register, register_success, change_password
from django.contrib.auth.views import (
    login,
    logout,
    password_reset,
    password_reset_done,
    password_reset_confirm,
    password_reset_complete,
)


urlpatterns = [
    url(r'^$', login, {'template_name': 'account/login.html'}, name='login'),
    url(r'^logout/$', logout_page, name='logout_page'),
    url(r'^register/$', register, name='register'),
    url(r'^register/success/$', register_success, name="success"),
    url(r'^change-password/$', change_password, name='change_password'),
    url(r'^reset-password/$', password_reset,
        {
            'template_name': 'account/reset_password.html',
            'post_reset_redirect':'account:password_reset_done',
            'email_template_name':'account/reset_password_email.html'
        },
        name='reset_password'),
    url(r'^reset-password/done/$', password_reset_done,
        {
            'template_name': "account/reset_password_done.html"
        },
        name='password_reset_done'),
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm,
        {
            'template_name':'account/reset_password_confirm.html',
            'post_reset_redirect':'account:password_reset_complete'
        },
        name='password_reset_confirm'),
    url(r'^reset-password/complete/$', password_reset_complete,
        {
            'template_name':'account/reset_password_complete.html'
        },
        name='password_reset_complete'),


]

worklog/urls.py
from django.conf.urls import url
from worklog.views import index, add_worklog, get_worklog, delete_worklog

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_worklog/$', add_worklog, name='add_worklog'),
    url(r'^get_worklog/$', get_worklog, name='get_worklog'),
    url(r'^delete_worklog/$', delete_worklog, name='delete_worklog'),
]

worklogger/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from worklogger.views import login_redirect


urlpatterns = [
    url(r'^home/$', login_redirect, name='login_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^worklog/', include('worklog.urls', namespace='worklog')),
]

account/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
#triggers
from django.db.models.signals import post_save

# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    description = models.CharField(max_length=100)
    city = models.CharField(max_length=100, default='')
    website = models.URLField(default='')
    phone = models.IntegerField(default=0)

    def __str__(self):
        return self.user.username

def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])


post_save.connect(create_profile, sender=User)

account/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
            )

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']
        if commit:
            user.save()

        return user

class EditProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'email',
            'password',
            )

account/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from account.forms import (
    RegistrationForm,
    EditProfileForm,
)
from django.contrib.auth import logout
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from pprint import pprint
from django.contrib.auth.decorators import login_required
from django.urls import reverse


# Create your views here.
def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = User.objects.create_user(
            username=form.cleaned_data['username'],
            password=form.cleaned_data['password1'],
            email=form.cleaned_data['email']
            )
            form.save()
            return redirect('/register/success/')
        else:
            args = {'form':form}
            pprint(args)
            return render(request, 'account/register.html', args)
    else:        
        form = RegistrationForm()
        args = {'form':form}
        return render(request, 'account/register.html', args)

def register_success(request):
    return render(request, 'registration/success.html',)


def change_password(request):
    if request.method=='POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect(reverse('account:view_profile'))
        else:
            args = {'form':form}
            return render(request, 'account/change_password.html', args)
    else:
        form = PasswordChangeForm(user=request.user)
        args = {'form':form}
        return render(request, 'account/change_password.html', args)

def logout_page(request):
    logout(request)
    return redirect('/account')

account/templates/base_generic.html
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link href="{% static 'font-awesome/css/font-awesome.css' %}" rel="stylesheet" />

    <link href="{% static 'css/animate.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

<!-- LOAD SPECIFIC CSS for the page      -->
    {% block css_import %}
    {% endblock %}

</head>

<body class="gray-bg">
    {%  block content %}
    {% endblock %}
</body>


<!-- LOAD SPECIFIC js for the page -->
{% block js_module %}
{% endblock %}
</html>

account/templates/navbar_side.html
<nav class="navbar-default navbar-static-side" role="navigation" id="sidenav">
  <div class="sidebar-collapse">
      <ul class="nav" id="side-menu">
          <li class="nav-header">
            <div style="height: 30px;"></div>
          </li>
          <!-- START OF MAIN MENUS -->
          <li data-toggle="popover" data-content="User Management">
            <a href="{% url 'worklog:index'%}" class="small"><i class="fa fa-user"></i><span class="nav-label">Home</span></a>
          </li>
          <!-- <li ><a href="#" class="small"><i class="fa fa-wrench"></i>Update Configuration</a></li> -->
      </ul>
  </div>
</nav>

account/templates/navbar_top.html
<div class="row border-bottom">
    <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">        
        </div>

        <ul class="nav navbar-top-links navbar-right">
            <li>
                <span class="m-r-sm text-muted welcome-message">Welcome {{ request.user.username }}.</span>
            </li>
            <li>
                <a href="{% url 'account:logout_page' %}">
                    <i class="fa fa-sign-out"></i> Log out
                </a>
            </li>
        </ul>

    </nav>
</div>