account/urls.py
from django.conf.urls import url, include
from account.views import logout_page, register, register_success, change_password
from django.contrib.auth.views import (
    login,
    logout,
    password_reset,
    password_reset_done,
    password_reset_confirm,
    password_reset_complete,
)


urlpatterns = [
    url(r'^$', login, {'template_name': 'account/login.html'}, name='login'),
    url(r'^logout/$', logout_page, name='logout_page'),
    url(r'^register/$', register, name='register'),
    url(r'^register/success/$', register_success, name="success"),
    url(r'^change-password/$', change_password, name='change_password'),
    url(r'^reset-password/$', password_reset,
        {
            'template_name': 'account/reset_password.html',
            'post_reset_redirect':'account:password_reset_done',
            'email_template_name':'account/reset_password_email.html'
        },
        name='reset_password'),
    url(r'^reset-password/done/$', password_reset_done,
        {
            'template_name': "account/reset_password_done.html"
        },
        name='password_reset_done'),
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm,
        {
            'template_name':'account/reset_password_confirm.html',
            'post_reset_redirect':'account:password_reset_complete'
        },
        name='password_reset_confirm'),
    url(r'^reset-password/complete/$', password_reset_complete,
        {
            'template_name':'account/reset_password_complete.html'
        },
        name='password_reset_complete'),


]

worklog/urls.py
from django.conf.urls import url
from worklog.views import index, add_worklog, get_worklog, delete_worklog

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_worklog/$', add_worklog, name='add_worklog'),
    url(r'^get_worklog/$', get_worklog, name='get_worklog'),
    url(r'^delete_worklog/$', delete_worklog, name='delete_worklog'),
]

worklogger/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from worklogger.views import login_redirect


urlpatterns = [
    url(r'^home/$', login_redirect, name='login_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^worklog/', include('worklog.urls', namespace='worklog')),
]

worklog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from project.models import Project
from django.utils import timezone
from django.contrib.auth.models import User
import datetime
# Create your models here.


class Worklog(models.Model):
    duration = models.IntegerField(default=1)
    user_id = models.ForeignKey(User)
    remarks = models.TextField()
    project_id = models.ForeignKey(Project, null=True, default=None, on_delete=models.SET_NULL)
    time_stamp = models.DateTimeField(default= datetime.datetime.now())

    def __str__(self):
        return self.remarks

worklog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.models import User
from django.utils import timezone
from django.http import HttpResponse
from project.models import Project
from django.db.models import Sum

from worklog.models import Worklog
from pprint import pprint
import json
from helpers import convert_timestamp_to_date
import datetime
# Create your views here.

def index(request):
    request.title = 'Work Log'
    request.page_title = 'Work Log'
    request.active_tab = 'worklog'
    projects = Project.objects.all()
    user = User.objects.get(id=request.user.id)
    total_hrs = Worklog.objects.filter(user_id = user).aggregate(total_hrs = Sum('duration'))

    args = {
        'total_hrs': total_hrs['total_hrs'],
        'projects': projects
    }
    return render(request, "worklog/index.html", args)


@csrf_exempt
def add_worklog(request):
    try:
        project = Project.objects.get(id=request.POST.get('project_id'))
        user = User.objects.get(id=request.user.id)
        worklog = Worklog.objects.create(
            duration=request.POST.get('duration'),
            user_id = user,
            remarks = request.POST.get('remarks'),
            project_id  = project
        )
        worklog.save()
        args = {
            "result":0
        }
        return HttpResponse(json.dumps(args), content_type='application/json')
    except:
        args= {
            "result":"error"
        }
        return HttpResponse(json.dumps(args), content_type='application/json')


@csrf_exempt
def get_worklog(request):
    if request.POST.get('datetime_input'):
        datetime_input = request.POST.get('datetime_input')
    else:
        datetime_input = timezone.now
    user = User.objects.get(id=request.user.id)
    worklog = Worklog.objects.filter(
        user_id = user
    ).values()
    list_result = []

    for row in worklog:
        tmp_dict = {}
        for k, v in row.iteritems():
            print type(v)
            if type(v) in (datetime, datetime.date, datetime.datetime, datetime.time):
                v = convert_timestamp_to_date(v)
            if k is "project_id_id":
                k.title

            # if type(v) is ""
            tmp_dict[k]=v

        list_result.append(tmp_dict)

    final_dt_result = {
        "draw":1,
        "recordsTotal":len(list_result),
        "recordsFiltered":len(list_result),
        "data": list_result
    }
    pprint(list_result)
    return HttpResponse(json.dumps(final_dt_result), content_type='application/json')

@csrf_exempt
def delete_worklog(request):
    worklog_id = request.POST.get('worklog_id')
    Worklog.objects.get(id=worklog_id).delete()
    args = {
        "result":0
    }
    return HttpResponse(json.dumps(args), content_type='application/json')

worklog/templates/worklog/index.html
{% extends 'base.html'%}

{%block title%}Dashboard{%endblock%}

{% block css_import %}
{% load static %}
<link href="{% static 'css/plugins/morris/morris-0.4.3.min.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Worklog</h5>
            </div>
            <div class="ibox-content">
                <form id="form-worklog" role="form" class="form-inline" method="post" onsubmit="return false">
                    <div class="form-group">
                      <label>Duration:</label>
                        <input type="text" name="duration" placeholder="Duration (Hours)" id="duration_hour" class="form-control">
                    </div>
                    <div class="form-group">
                      <label>Project:</label>
                        <select class="form-control" name="project_id" required>
                            <option value="">SELECT PROJECT</option>
                            {% for row in projects%}
                            <option value="{{row.id}}">{{row.title}}</option>
                            {%endfor%}
                        </select>
                    </div>
                    <div class="form-group">
                      <label>Remark:</label>
                        <input type="text" name="remarks" placeholder="Remarks" id="txt-remarks" class="form-control">
                    </div>
                    <button class="btn btn-success pull-right"  type="submit" > Add Worklog</button>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
   <div class="row">
       <div class="col-lg-12">
       <div class="ibox float-e-margins">
           <div class="ibox-title">
               <h5>Work Log Table</h5>
               <div class="ibox-tools">
                  <input type="text" class="form-control" name="datetime" id="dt_datetime">
               </div>
           </div>
           <div class="ibox-content">
             Total Log for the Day: {{total_hrs}}<br/>
           <table class="table table-striped table-bordered table-hover" id="dt_worklog">
           <thead>
           <tr>
               <th>Duration</th>
               <th>Project</th>
               <th>Remarks</th>
               <th>Timestamp</th>
               <th></th>
           </tr>
           </thead>
           <tbody>
           </tfoot>
           </table>

           </div>
       </div>
    </div>
   </div>
</div>

{% endblock %}

{% block js_module %}

<script>

var dt_worklog = $("#dt_worklog").dataTable({
  "responsive": true,
  "dom": 'T<"clear">lfrtip',
  "processing": true,
  "serverSide": true,
  "ajax": {
      "url": "{% url 'worklog:get_worklog' %}",
      "type": "POST"
  },
  "columns": [
      { "data": "duration" },
      { "data": "project_id_id" },
      { "data": "remarks" },
      { "data":"time_stamp",
      'render':function(data){
        return data
        }
      },
      {
			'data': 'id',
			'orderable': false,
			'sClass': 'action_btns',
			'render': function (data, type, row) {
  				return '<input type="hidden" name="id" value="'+ data +'"> ' +
  				'<button type="button" class="btn btn-danger btn-sm btn_delete btn-outline" data-id="'+data+'"><i class="fa fa-trash-o"></i> Delete</button>';
			  }
      }
  ],
  'fnDrawCallback': function( oSettings ) {
  }
});

$("#form-worklog").submit(function(){
    var data = $("#form-worklog").serialize();
    $.post("{% url 'worklog:add_worklog' %}", data, function(resp){
       if(parseInt(resp['result']) == 0){
          swal("Success!");
       }else{
          swal("Something Went wrong!");
       }

    });
});


$(document).on("click",".btn_delete", function(){
  var worklog_id = $(this).attr("data-id");
  swal_confirm('Delete selected record(s)?', "" , function() {
    $.post("{% url 'worklog:delete_worklog' %}", {worklog_id:worklog_id}, function(){})
  });
  dt_worklog.ajax.draw();
});

</script>
{% endblock %}